name: On Push Example

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print a message
        run: echo "A new push was detected"

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: my-first-aws-app/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: my-first-aws-app

      - name: Run jest tests
        run: npm test
        working-directory: my-first-aws-app

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code for deployment
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::869036203214:role/github-actions-ecs-deploy
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image
        working-directory: my-first-aws-app
        run: |
          IMAGE_URI=869036203214.dkr.ecr.eu-north-1.amazonaws.com/my-aws-apps:${{ github.sha }}
          docker build -f apps/aws/Dockerfile -t $IMAGE_URI .
          docker push $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Render ECS task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs/task-definition.json
          container-name: my-container
          image: ${{ env.IMAGE_URI }}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: my-aws-task-definition-service-igvnsldq
          cluster: my-aws-cluster
          wait-for-service-stability: true





